In [1]:
import numpy as np

In [2]:
pred_passadas = np.array([np.random.random(15) for x in range(0,7)])
pred_passadas

array([[0.31602643, 0.65198229, 0.43623013, 0.97364362, 0.66042016,
        0.31981427, 0.07844003, 0.81900019, 0.82700363, 0.26710448,
        0.28824283, 0.50211111, 0.43373666, 0.67236514, 0.25681944],
       [0.55380934, 0.44289705, 0.10957695, 0.2746475 , 0.90262525,
        0.23887059, 0.75420219, 0.7455169 , 0.66063098, 0.06203538,
        0.3583715 , 0.95605758, 0.72162683, 0.8558803 , 0.20912905],
       [0.58829699, 0.31381234, 0.88262239, 0.52531995, 0.24460288,
        0.34512186, 0.45427432, 0.85132328, 0.61404668, 0.30902789,
        0.84884571, 0.73793054, 0.42337053, 0.30883242, 0.95244383],
       [0.79891864, 0.40594554, 0.61277891, 0.12910577, 0.08416675,
        0.58808449, 0.40518796, 0.64784832, 0.3080962 , 0.67459432,
        0.78545423, 0.33055188, 0.66881288, 0.65059889, 0.73382461],
       [0.61042222, 0.33295476, 0.14180275, 0.88833291, 0.50581694,
        0.1820251 , 0.65303124, 0.40322417, 0.75256291, 0.04591013,
        0.27223588, 0.90279545, 0.42527105, 

In [3]:
pred_passadas.shape

(7, 15)

In [4]:
pred = np.random.random(7)
pred

array([0.33138679, 0.07189746, 0.84960644, 0.73042655, 0.90907542,
       0.09637081, 0.87040026])

In [5]:
a = np.insert(pred_passadas, 0, pred, axis=1)

In [6]:
a.shape

(7, 16)

In [9]:
b = pred_passadas.copy()

In [10]:
b

array([[0.31602643, 0.65198229, 0.43623013, 0.97364362, 0.66042016,
        0.31981427, 0.07844003, 0.81900019, 0.82700363, 0.26710448,
        0.28824283, 0.50211111, 0.43373666, 0.67236514, 0.25681944],
       [0.55380934, 0.44289705, 0.10957695, 0.2746475 , 0.90262525,
        0.23887059, 0.75420219, 0.7455169 , 0.66063098, 0.06203538,
        0.3583715 , 0.95605758, 0.72162683, 0.8558803 , 0.20912905],
       [0.58829699, 0.31381234, 0.88262239, 0.52531995, 0.24460288,
        0.34512186, 0.45427432, 0.85132328, 0.61404668, 0.30902789,
        0.84884571, 0.73793054, 0.42337053, 0.30883242, 0.95244383],
       [0.79891864, 0.40594554, 0.61277891, 0.12910577, 0.08416675,
        0.58808449, 0.40518796, 0.64784832, 0.3080962 , 0.67459432,
        0.78545423, 0.33055188, 0.66881288, 0.65059889, 0.73382461],
       [0.61042222, 0.33295476, 0.14180275, 0.88833291, 0.50581694,
        0.1820251 , 0.65303124, 0.40322417, 0.75256291, 0.04591013,
        0.27223588, 0.90279545, 0.42527105, 

In [7]:
a

array([[0.33138679, 0.31602643, 0.65198229, 0.43623013, 0.97364362,
        0.66042016, 0.31981427, 0.07844003, 0.81900019, 0.82700363,
        0.26710448, 0.28824283, 0.50211111, 0.43373666, 0.67236514,
        0.25681944],
       [0.07189746, 0.55380934, 0.44289705, 0.10957695, 0.2746475 ,
        0.90262525, 0.23887059, 0.75420219, 0.7455169 , 0.66063098,
        0.06203538, 0.3583715 , 0.95605758, 0.72162683, 0.8558803 ,
        0.20912905],
       [0.84960644, 0.58829699, 0.31381234, 0.88262239, 0.52531995,
        0.24460288, 0.34512186, 0.45427432, 0.85132328, 0.61404668,
        0.30902789, 0.84884571, 0.73793054, 0.42337053, 0.30883242,
        0.95244383],
       [0.73042655, 0.79891864, 0.40594554, 0.61277891, 0.12910577,
        0.08416675, 0.58808449, 0.40518796, 0.64784832, 0.3080962 ,
        0.67459432, 0.78545423, 0.33055188, 0.66881288, 0.65059889,
        0.73382461],
       [0.90907542, 0.61042222, 0.33295476, 0.14180275, 0.88833291,
        0.50581694, 0.1820251 , 

In [ ]:
shifted_pred = np.delete(a, a.shape[1]-1, axis=1)

In [ ]:
shifted_pred

In [ ]:
pred_mean = np.mean(shifted_pred, axis=1)

In [ ]:
pred_mean

In [ ]:
pred_mean[0:3].max()

In [ ]:
pred_mean[4:6].max()

In [ ]:
pred_resume = [pred_mean[0:3].max(), pred_mean[3], pred_mean[4], pred_mean[5:7].max()]
pred_resume

In [ ]:
np.argmax(pred_resume)